In [1]:
import pandas as pd
count_all=[]

In [2]:
df24=pd.read_csv('cpbl2024.csv')
df24.columns= [
    'No',
    'date',
    'day',
    'stadium',
    'visitor',
    'home',
    'audience'
]
df24.head()

    No        date day stadium       visitor          home  audience
0  213  2024/10/11   五   樂天桃園   統一7-ELEVEn獅          樂天桃猿       4947
1  344  2024/10/10   四     新莊   統一7-ELEVEn獅          富邦悍將       7112
2  342  2024/10/10   四    澄清湖          樂天桃猿          台鋼雄鷹       8307
3  218   2024/10/9   三     台南           味全龍   統一7-ELEVEn獅       5140
4  217   2024/10/9   三   樂天桃園          中信兄弟          樂天桃猿       8853

In [3]:
stadium=df24['stadium'].unique()
stadium

array(['樂天桃園 ', '新莊 ', '澄清湖 ', '台南 ', '天母 ', '洲際 ', '嘉義市 ', '台北大巨蛋 ',
       '台東 ', '斗六 ', '花蓮 '], dtype=object)

In [4]:
df24['month']=pd.to_datetime(df24['date']).dt.month
df24['month']
df24['year']=pd.to_datetime(df24['date']).dt.year
df24['year']

0      2024
1      2024
2      2024
3      2024
4      2024
       ...
355    2024
356    2024
357    2024
358    2024
359    2024
Name: year, Length: 360, dtype: int32

In [5]:
count24=df24.groupby(['year','month','stadium']).size().reset_index(name='count')
count24

    year  month stadium  count
0   2024      3  台北大巨蛋       2
1   2024      3     台南       1
2   2024      4  台北大巨蛋       5
3   2024      4     台南      12
4   2024      4     天母      10
..   ...    ...     ...    ...
56  2024     10     天母       2
57  2024     10     新莊       4
58  2024     10   樂天桃園       2
59  2024     10     洲際       3
60  2024     10    澄清湖       1

[61 rows x 4 columns]

In [6]:
count_all.append(count24)
count_all

[    year  month stadium  count
 0   2024      3  台北大巨蛋       2
 1   2024      3     台南       1
 2   2024      4  台北大巨蛋       5
 3   2024      4     台南      12
 4   2024      4     天母      10
 ..   ...    ...     ...    ...
 56  2024     10     天母       2
 57  2024     10     新莊       4
 58  2024     10   樂天桃園       2
 59  2024     10     洲際       3
 60  2024     10    澄清湖       1

 [61 rows x 4 columns]]

In [7]:
df25=pd.read_csv('cpbl2025.csv')
df25.columns= [
    'No',
    'date',
    'day',
    'stadium',
    'visitor',
    'home',
    'audience'
]
df25.head()

    No       date day stadium       visitor          home  audience
0  343  2025/10/6   一    澄清湖          樂天桃猿   統一7-ELEVEn獅       7051
1  314  2025/10/5   日     洲際   統一7-ELEVEn獅          中信兄弟      11925
2  239  2025/10/5   日    澄清湖           味全龍          台鋼雄鷹      10155
3  315  2025/10/4   六     新莊          樂天桃猿          富邦悍將      10012
4  187  2025/10/4   六    澄清湖          中信兄弟          台鋼雄鷹      12438

In [8]:
stadium=df25['stadium'].unique()
stadium

array(['澄清湖 ', '洲際 ', '新莊 ', '天母 ', '嘉義市 ', '樂天桃園 ', '台北大巨蛋 ', '台東 ',
       '斗六 ', '台南 ', '花蓮 '], dtype=object)

In [9]:
df25['month']=pd.to_datetime(df25['date']).dt.month
df25['month']
df25['year']=pd.to_datetime(df25['date']).dt.year
df25['year']

0      2025
1      2025
2      2025
3      2025
4      2025
       ...
355    2025
356    2025
357    2025
358    2025
359    2025
Name: year, Length: 360, dtype: int32

In [10]:
count25=df25.groupby(['year','month','stadium']).size().reset_index(name='count')
count25

    year  month stadium  count
0   2025      3  台北大巨蛋       2
1   2025      3     台南       1
2   2025      4  台北大巨蛋      13
3   2025      4     台南       9
4   2025      4     天母       6
5   2025      4     新莊       9
6   2025      4   樂天桃園       7
7   2025      4     洲際       9
8   2025      4    澄清湖      10
9   2025      5  台北大巨蛋       3
10  2025      5     台南       7
11  2025      5    嘉義市       2
12  2025      5     天母       5
13  2025      5     新莊       9
14  2025      5   樂天桃園       9
15  2025      5     洲際       8
16  2025      5    澄清湖      12
17  2025      5     花蓮       2
18  2025      6  台北大巨蛋       4
19  2025      6     台南       6
20  2025      6    嘉義市       2
21  2025      6     天母      10
22  2025      6     新莊       8
23  2025      6   樂天桃園      12
24  2025      6     洲際       8
25  2025      6    澄清湖       6
26  2025      6     花蓮       1
27  2025      7  台北大巨蛋       7
28  2025      7     天母       5
29  2025      7     斗六       2
30  2025      7     新莊       7
31  2025      7   樂天桃園       7
32  2025      7     洲際       5
33  2025      7    澄清湖       8
34  2025      8  台北大巨蛋      21
35  2025      8     台東       4
36  2025      8     天母       5
37  2025      8     新莊      12
38  2025      8   樂天桃園       7
39  2025      8     洲際       5
40  2025      8    澄清湖      13
41  2025      9  台北大巨蛋      16
42  2025      9    嘉義市       2
43  2025      9     天母       7
44  2025      9     新莊      10
45  2025      9   樂天桃園       6
46  2025      9     洲際       7
47  2025      9    澄清湖      11
48  2025     10    嘉義市       2
49  2025     10     天母       1
50  2025     10     新莊       2
51  2025     10     洲際       3
52  2025     10    澄清湖       5

In [11]:
count_all.append(count25)
count_all

[    year  month stadium  count
 0   2024      3  台北大巨蛋       2
 1   2024      3     台南       1
 2   2024      4  台北大巨蛋       5
 3   2024      4     台南      12
 4   2024      4     天母      10
 ..   ...    ...     ...    ...
 56  2024     10     天母       2
 57  2024     10     新莊       4
 58  2024     10   樂天桃園       2
 59  2024     10     洲際       3
 60  2024     10    澄清湖       1

 [61 rows x 4 columns],
     year  month stadium  count
 0   2025      3  台北大巨蛋       2
 1   2025      3     台南       1
 2   2025      4  台北大巨蛋      13
 3   2025      4     台南       9
 4   2025      4     天母       6
 5   2025      4     新莊       9
 6   2025      4   樂天桃園       7
 7   2025      4     洲際       9
 8   2025      4    澄清湖      10
 9   2025      5  台北大巨蛋       3
 10  2025      5     台南       7
 11  2025      5    嘉義市       2
 12  2025      5     天母       5
 13  2025      5     新莊       9
 14  2025      5   樂天桃園       9
 15  2025      5     洲際       8
 16  2025      5    澄清湖      12
 17  2025      5     花蓮       2
 18  2025      6  台北大巨蛋       4
 19  2025      6     台南       6
 20  2025      6    嘉義市       2
 21  2025      6     天母      10
 22  2025      6     新莊       8
 23  2025      6   樂天桃園      12
 24  2025      6     洲際       8
 25  2025      6    澄清湖       6
 26  2025      6     花蓮       1
 27  2025      7  台北大巨蛋       7
 28  2025      7     天母       5
 29  2025      7     斗六       2
 30  2025      7     新莊       7
 31  2025      7   樂天桃園       7
 32  2025      7     洲際       5
 33  2025      7    澄清湖       8
 34  2025      8  台北大巨蛋      21
 35  2025      8     台東       4
 36  2025      8     天母       5
 37  2025      8     新莊      12
 38  2025      8   樂天桃園       7
 39  2025      8     洲際       5
 40  2025      8    澄清湖      13
 41  2025      9  台北大巨蛋      16
 42  2025      9    嘉義市       2
 43  2025      9     天母       7
 44  2025      9     新莊      10
 45  2025      9   樂天桃園       6
 46  2025      9     洲際       7
 47  2025      9    澄清湖      11
 48  2025     10    嘉義市       2
 49  2025     10     天母       1
 50  2025     10     新莊       2
 51  2025     10     洲際       3
 52  2025     10    澄清湖       5]

In [12]:
df26=pd.read_csv('cpbl2026.csv')
df26.columns= [
    'No',
    'date',
    'day',
    'stadium',
    'visitor',
    'home',
    'audience'
]
df26.head()

    No       date day stadium       visitor   home  audience
0  274  2026/10/6   二   樂天桃園          富邦悍將   樂天桃猿       7621
1   14  2026/10/5   一     洲際   統一7-ELEVEn獅   中信兄弟       7184
2  270  2026/10/4   日     洲際          台鋼雄鷹   中信兄弟      20000
3  252  2026/10/4   日     新莊   統一7-ELEVEn獅   富邦悍將      11110
4  251  2026/10/4   日   樂天桃園           味全龍   樂天桃猿      11645

In [13]:
stadium=df26['stadium'].unique()
stadium

array(['樂天桃園 ', '洲際 ', '新莊 ', '亞太主 ', '澄清湖 ', '天母 ', '台北大巨蛋 ', '嘉義市 ',
       '台東 ', '斗六 ', '花蓮 '], dtype=object)

In [14]:
df26['month']=pd.to_datetime(df26['date']).dt.month
df26['month']
df26['year']=pd.to_datetime(df26['date']).dt.year
df26['year']

0      2026
1      2026
2      2026
3      2026
4      2026
       ...
355    2026
356    2026
357    2026
358    2026
359    2026
Name: year, Length: 360, dtype: int32

In [15]:
count26=df26.groupby(['year','month','stadium']).size().reset_index(name='count')
count26

    year  month stadium  count
0   2026      3    亞太主       2
1   2026      3  台北大巨蛋       2
2   2026      3   樂天桃園       1
3   2026      3     洲際       2
4   2026      4    亞太主       9
5   2026      4    嘉義市       1
6   2026      4     天母       9
7   2026      4     新莊      10
8   2026      4   樂天桃園      10
9   2026      4     洲際       9
10  2026      4    澄清湖       9
11  2026      5    亞太主       8
12  2026      5  台北大巨蛋      13
13  2026      5    嘉義市       4
14  2026      5     天母       9
15  2026      5     新莊      10
16  2026      5   樂天桃園      10
17  2026      5     洲際       4
18  2026      5    澄清湖       6
19  2026      5     花蓮       2
20  2026      6    亞太主       4
21  2026      6  台北大巨蛋       5
22  2026      6     天母       6
23  2026      6     新莊       7
24  2026      6   樂天桃園       7
25  2026      6     洲際       8
26  2026      6    澄清湖      10
27  2026      7    亞太主      10
28  2026      7  台北大巨蛋       8
29  2026      7     台東       2
30  2026      7    嘉義市       2
31  2026      7     天母       3
32  2026      7     斗六       2
33  2026      7     新莊       4
34  2026      7   樂天桃園       5
35  2026      7     洲際       9
36  2026      7    澄清湖       6
37  2026      8    亞太主       6
38  2026      8  台北大巨蛋      15
39  2026      8     台東       4
40  2026      8    嘉義市       1
41  2026      8     天母       5
42  2026      8     新莊       8
43  2026      8   樂天桃園       2
44  2026      8     洲際       7
45  2026      8    澄清湖       6
46  2026      9    亞太主       8
47  2026      9  台北大巨蛋      15
48  2026      9    嘉義市       2
49  2026      9     天母       7
50  2026      9     新莊       8
51  2026      9   樂天桃園      14
52  2026      9     洲際       6
53  2026      9    澄清湖       6
54  2026     10    亞太主       1
55  2026     10     天母       1
56  2026     10     新莊       3
57  2026     10   樂天桃園       3
58  2026     10     洲際       2
59  2026     10    澄清湖       2

In [16]:
count_all.append(count26)
count_all

[    year  month stadium  count
 0   2024      3  台北大巨蛋       2
 1   2024      3     台南       1
 2   2024      4  台北大巨蛋       5
 3   2024      4     台南      12
 4   2024      4     天母      10
 ..   ...    ...     ...    ...
 56  2024     10     天母       2
 57  2024     10     新莊       4
 58  2024     10   樂天桃園       2
 59  2024     10     洲際       3
 60  2024     10    澄清湖       1

 [61 rows x 4 columns],
     year  month stadium  count
 0   2025      3  台北大巨蛋       2
 1   2025      3     台南       1
 2   2025      4  台北大巨蛋      13
 3   2025      4     台南       9
 4   2025      4     天母       6
 5   2025      4     新莊       9
 6   2025      4   樂天桃園       7
 7   2025      4     洲際       9
 8   2025      4    澄清湖      10
 9   2025      5  台北大巨蛋       3
 10  2025      5     台南       7
 11  2025      5    嘉義市       2
 12  2025      5     天母       5
 13  2025      5     新莊       9
 14  2025      5   樂天桃園       9
 15  2025      5     洲際       8
 16  2025      5    澄清湖      12
 17  2025      5     花蓮       2
 18  2025      6  台北大巨蛋       4
 19  2025      6     台南       6
 20  2025      6    嘉義市       2
 21  2025      6     天母      10
 22  2025      6     新莊       8
 23  2025      6   樂天桃園      12
 24  2025      6     洲際       8
 25  2025      6    澄清湖       6
 26  2025      6     花蓮       1
 27  2025      7  台北大巨蛋       7
 28  2025      7     天母       5
 29  2025      7     斗六       2
 30  2025      7     新莊       7
 31  2025      7   樂天桃園       7
 32  2025      7     洲際       5
 33  2025      7    澄清湖       8
 34  2025      8  台北大巨蛋      21
 35  2025      8     台東       4
 36  2025      8     天母       5
 37  2025      8     新莊      12
 38  2025      8   樂天桃園       7
 39  2025      8     洲際       5
 40  2025      8    澄清湖      13
 41  2025      9  台北大巨蛋      16
 42  2025      9    嘉義市       2
 43  2025      9     天母       7
 44  2025      9     新莊      10
 45  2025      9   樂天桃園       6
 46  2025      9     洲際       7
 47  2025      9    澄清湖      11
 48  2025     10    嘉義市       2
 49  2025     10     天母       1
 50  2025     10     新莊       2
 51  2025     10     洲際       3
 52  2025     10    澄清湖       5,
     year  month stadium  count
 0   2026      3    亞太主       2
 1   2026      3  台北大巨蛋       2
 2   2026      3   樂天桃園       1
 3   2026      3     洲際       2
 4   2026      4    亞太主       9
 5   2026      4    嘉義市       1
 6   2026      4     天母       9
 7   2026      4     新莊      10
 8   2026      4   樂天桃園      10
 9   2026      4     洲際       9
 10  2026      4    澄清湖       9
 11  2026      5    亞太主       8
 12  2026      5  台北大巨蛋      13
 13  2026      5    嘉義市       4
 14  2026      5     天母       9
 15  2026      5     新莊      10
 16  2026      5   樂天桃園      10
 17  2026      5     洲際       4
 18  2026      5    澄清湖       6
 19  2026      5     花蓮       2
 20  2026      6    亞太主       4
 21  2026      6  台北大巨蛋       5
 22  2026      6     天母       6
 23  2026      6     新莊       7
 24  2026      6   樂天桃園       7
 25  2026      6     洲際       8
 26  2026      6    澄清湖      10
 27  2026      7    亞太主      10
 28  2026      7  台北大巨蛋       8
 29  2026      7     台東       2
 30  2026      7    嘉義市       2
 31  2026      7     天母       3
 32  2026      7     斗六       2
 33  2026      7     新莊       4
 34  2026      7   樂天桃園       5
 35  2026      7     洲際       9
 36  2026      7    澄清湖       6
 37  2026      8    亞太主       6
 38  2026      8  台北大巨蛋      15
 39  2026      8     台東       4
 40  2026      8    嘉義市       1
 41  2026      8     天母       5
 42  2026      8     新莊       8
 43  2026      8   樂天桃園       2
 44  2026      8     洲際       7
 45  2026      8    澄清湖       6
 46  2026      9    亞太主       8
 47  2026      9  台北大巨蛋      15
 48  2026      9    嘉義市       2
 49  2026      9     天母       7
 50  2026      9     新莊       8
 51  2026      9   樂天桃園      14
 52  2026      9     洲際       6
 53  2026      9    澄清湖       6
 54  2026     10    亞太主       1
 55  2026     10     天母       1
 56  2026     10     新莊       3
 57  2026     10   樂天桃園       3
 58  2026     10     洲際       2
 59  2026     10    澄清湖       2]

In [18]:
df = pd.concat(count_all, ignore_index=True)

df.columns = [
    '年',
    '月',
    '球場',
    '試合数'
]
df.to_csv('games_per_stadium.csv', index=False, encoding='utf-8-sig')